In [3]:
import tensorflow as tf
hello = tf.constant('Hello, Tensorflow!',name='greetings')
print(hello)
sess=tf.Session()
print(sess.run(hello))
rank=[[1,2,3],[4,5,6]]
print(rank)

Tensor("greetings_1:0", shape=(), dtype=string)
b'Hello, Tensorflow!'
[[1, 2, 3], [4, 5, 6]]


In [6]:
a=tf.constant(10)
b=tf.constant(20)
c=tf.add(a,b)
print(c)
print(sess.run(c))

Tensor("Add_1:0", shape=(), dtype=int32)
30


In [23]:
X=tf.placeholder(tf.float32,[None,3])
x_data =[[1,2,3],[4,5,6]]

W=tf.Variable(tf.random_normal([3,2]))
b=tf.Variable(tf.random_normal([2,1]))


In [24]:
sess.run(tf.global_variables_initializer())
print("======x_data======")
print(x_data)
print("======W=======")
print(sess.run(W))
print("======b========")
print(sess.run(b))
print("======expr======")
expr=tf.add(tf.matmul(X,W),b)
print(sess.run(expr,feed_dict={X:x_data}))
sess.close()

======x_data======
[[1, 2, 3], [4, 5, 6]]
======W=======
[[ 1.3691442   0.1745093 ]
 [ 1.6806389  -0.5346771 ]
 [-1.5147308  -0.75150627]]
======b========
[[2.7085204]
 [1.463561 ]]
======expr======
[[ 2.89475   -0.4408431]
 [ 6.2549477 -5.0208244]]


In [17]:
print(sess.run(tf.matmul(b,W)))

[[-0.8005515  -0.51501644]]
